version: '2'
services:
  mysql:
    image: mysql:5.7.27
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password
  #        working_dir: /application
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssWord123
      - MYSQL_DATABASE=db001
      - MYSQL_USER=root
      - MYSQL_PASSWORD=p@ssWord123
    ports:
      - "8082:3306"
  website:
      container_name: simple-cms
      image: pensiero/apache-php-mysql
      build:
        context: ./
      volumes:
        - ~/Documents/Projects/PHP/TUTS/simple-cms/:/var/www/html/
      ports:
        - 3030:80
      depends_on:
        - mysql
