<div class="space-bottom space-top">
    <a href="<?php echo BASE_URL; ?>contacts/index.php" class="btn btn-sm btn-default">Conacts Listing Page</a>
</div>

<form action="<?php echo $_SERVER['REQUEST_URI']; ?>" method="post">
    <div class="form-group">
        <label for="fullname">Full Name: </label>
        <input type="text" class="form-control" name="fullname" id="fullname"<?php echo $inputs != "" ? ' value="' . $inputs->fullname .'"' : ''; ?>>
    </div>
    <div class="form-group">
        <label for="email">Email: </label>
        <input type="text" class="form-control" name="email" id="email"<?php echo $inputs != "" ? ' value="' . $inputs->email .'"' : ''; ?>>
    </div>
    <div class="form-group">
        <input type="submit" value="Edit Contact" class="btn btn-primary">
    </div>
    <input type="hidden" name="token" value="<?php echo md5("contact.edit"); ?>">
</form>
