<div class="space-bottom space-top">
    <a href="<?php echo BASE_URL; ?>contacts/index.php" class="btn btn-sm btn-default">Conacts Listing Page</a>
    <a href="<?php echo BASE_URL; ?>contacts/add.php" class="btn btn-sm btn-default">Add New Contacts</a>
</div>

<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <tr>
            <th>ID</th>
            <td><?php echo $contact->id ?></td>
        </tr>
        <tr>
            <th>Full Name</th>
            <td><?php echo $contact->fullname ?></td>
        </tr>
        <tr>
            <th>Email</th>
            <td><?php echo $contact->email ?></td>
        </tr>
        <tr>
            <th>Created At</th>
            <td><?php echo $contact->created_at ?></td>
        </tr>
        <tr>
            <th>Modified At</th>
            <td><?php echo $contact->modified_at ?></td>
        </tr>
    </table>
</div>
